{{- if not .Values.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grantex.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "grantex.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ required "externalDatabase.url is required when existingSecret is not set" .Values.externalDatabase.url | quote }}
  REDIS_URL: {{ required "externalRedis.url is required when existingSecret is not set" .Values.externalRedis.url | quote }}
  ADMIN_API_KEY: {{ required "adminApiKey is required when existingSecret is not set" .Values.adminApiKey | quote }}
  VAULT_ENCRYPTION_KEY: {{ required "vaultEncryptionKey is required when existingSecret is not set" .Values.vaultEncryptionKey | quote }}
  {{- if .Values.metrics.enabled }}
  METRICS_API_KEY: {{ required "metrics.apiKey is required when metrics are enabled and existingSecret is not set" .Values.metrics.apiKey | quote }}
  {{- end }}
  RSA_PRIVATE_KEY: |-
{{ required "rsaPrivateKey is required when existingSecret is not set" .Values.rsaPrivateKey | nindent 4 }}
{{- end }}
