import { ulid } from 'ulid';

export const newAgentId = (): string => `ag_${ulid()}`;
export const newGrantId = (): string => `grnt_${ulid()}`;
export const newTokenId = (): string => `tok_${ulid()}`;
export const newRefreshTokenId = (): string => `ref_${ulid()}`;
export const newAuthRequestId = (): string => `areq_${ulid()}`;
export const newAuditEntryId = (): string => `alog_${ulid()}`;
export const newDeveloperId = (): string => `dev_${ulid()}`;
export const newWebhookId = (): string => `wh_${ulid()}`;
export const newSubscriptionId = (): string => `sub_${ulid()}`;
export const newPolicyId = (): string => `pol_${ulid()}`;
export const newAnomalyId = (): string => `anm_${ulid()}`;
export const newScimTokenId = (): string => `scimtok_${ulid()}`;
export const newScimUserId = (): string => `scimuser_${ulid()}`;
export const newVaultCredentialId = (): string => `vault_${ulid()}`;
export const newBudgetAllocationId = (): string => `bdg_${ulid()}`;
export const newBudgetTransactionId = (): string => `btx_${ulid()}`;
export const newUsageDailyId = (): string => `usg_${ulid()}`;
export const newPolicyBundleId = (): string => `pbnd_${ulid()}`;
export const newSigningKeyId = (): string => `key_${ulid()}`;
export const newWebAuthnCredentialId = (): string => `cred_${ulid()}`;
export const newWebAuthnChallengeId = (): string => `wac_${ulid()}`;
export const newVerifiableCredentialId = (): string => `vc_${ulid()}`;
export const newStatusListId = (): string => `vcsl_${ulid()}`;
export const newPresentationId = (): string => `pres_${ulid()}`;
export const newSsoConnectionId = (): string => `sso_${ulid()}`;
export const newSsoSessionId = (): string => `ssosess_${ulid()}`;
