/**
 * Platform signing keys: the key that signs grant tokens, OAuth access tokens
 * and the other platform JWTs, plus the older keys that still verify them.
 *
 * Two stores:
 *
 * - `env` (default): the signing key comes from `RSA_PRIVATE_KEY` (RS256) or
 *   `EC_PRIVATE_KEY` (ES256, P-256), selected by `JWT_SIGNING_ALG`, or is
 *   generated at start when `AUTO_GENERATE_KEYS=true`. A configured key for
 *   the other algorithm is published for verification only, so a new key can
 *   be published before it signs. Keys that no longer sign are listed in
 *   `JWT_RETIRED_PUBLIC_KEYS` (a public JWK Set) for as long as tokens they
 *   signed may be presented.
 * - `postgres`: keys are generated by the service and stored in
 *   `platform_signing_keys`, private keys encrypted with
 *   `VAULT_ENCRYPTION_KEY`. Rotation retires the active key (erasing its
 *   private key) and inserts a new one; retired keys stay in the JWK Set for
 *   `SIGNING_KEY_RETIRED_GRACE_SECONDS`. Every instance reloads the key set
 *   periodically and when a token names an unknown `kid`.
 *
 * Verification is fail-closed: the header `alg` must be RS256 or ES256, the
 * `kid` must name a known key, and that key must have been published for
 * exactly that algorithm. There is no fallback to another key.
 */
import {
  calculateJwkThumbprint,
  exportJWK,
  generateKeyPair,
  importJWK,
  importPKCS8,
  type CryptoKey as KeyLike,
  type JWK,
  type JWTHeaderParameters,
} from 'jose';
import type postgres from 'postgres';
import { decrypt, encrypt } from './vault-crypto.js';
import {
  isSigningAlgorithm,
  keyTypeForAlgorithm,
  SIGNING_ALGORITHMS,
  type SigningAlgorithm,
} from './signing-algorithms.js';

export { SIGNING_ALGORITHMS, isSigningAlgorithm, type SigningAlgorithm } from './signing-algorithms.js';

type Sql = ReturnType<typeof postgres>;

/** Why a key could not be loaded or a token's key could not be resolved. */
export type SigningKeyErrorCode =
  | 'no_signing_key'
  | 'invalid_key'
  | 'duplicate_kid'
  | 'unsupported_alg'
  | 'missing_kid'
  | 'unknown_kid'
  | 'alg_key_mismatch'
  | 'keys_not_initialized';

export class SigningKeyError extends Error {
  readonly code: SigningKeyErrorCode;

  constructor(code: SigningKeyErrorCode, message: string) {
    super(message);
    this.name = 'SigningKeyError';
    this.code = code;
  }
}

export interface SigningKey {
  kid: string;
  alg: SigningAlgorithm;
  /** Public JWK as published: public members plus `kid`, `alg` and `use`. */
  publicJwk: JWK & { kid: string; alg: SigningAlgorithm; use: 'sig' };
  publicKey: KeyLike;
  /** Present only for the active key. */
  privateKey: KeyLike | null;
  status: 'active' | 'retired';
}

export interface ActiveSigningKey extends SigningKey {
  privateKey: KeyLike;
  status: 'active';
}

const PRIVATE_JWK_MEMBERS = ['d', 'p', 'q', 'dp', 'dq', 'qi', 'oth', 'k'] as const;
const MIN_RSA_MODULUS_BITS = 2048;
const KID_RE = /^[A-Za-z0-9._:-]{1,128}$/;

/** A set of keys with one active signer and unique `kid`s. */
export class SigningKeyRing {
  readonly active: ActiveSigningKey;
  readonly #byKid: Map<string, SigningKey>;

  constructor(active: ActiveSigningKey, verificationOnly: readonly SigningKey[] = []) {
    this.active = active;
    this.#byKid = new Map([[active.kid, active]]);
    for (const key of verificationOnly) {
      if (this.#byKid.has(key.kid)) {
        throw new SigningKeyError('duplicate_kid', `Signing key id "${key.kid}" is used by more than one key`);
      }
      this.#byKid.set(key.kid, key);
    }
  }

  get(kid: string): SigningKey | undefined {
    return this.#byKid.get(kid);
  }

  /** Active key first, then verification-only keys in load order. */
  keys(): SigningKey[] {
    return [...this.#byKid.values()];
  }
}

// ─── Key material helpers ────────────────────────────────────────────────────

function base64UrlByteLength(value: string): number {
  return Buffer.from(value, 'base64url').length;
}

/**
 * Throw unless `jwk` is a public key usable with `alg`: the right key type
 * (and curve), no private members, `use` absent or `sig`, `alg` absent or
 * equal to `alg`, and an RSA modulus of at least 2048 bits.
 */
export function assertPublicJwkForAlgorithm(jwk: Record<string, unknown>, alg: SigningAlgorithm): void {
  for (const member of PRIVATE_JWK_MEMBERS) {
    if (member in jwk) {
      throw new SigningKeyError('invalid_key', 'A published signing key must not contain private key members');
    }
  }
  if (jwk['use'] !== undefined && jwk['use'] !== 'sig') {
    throw new SigningKeyError('invalid_key', 'A signing key must have use "sig"');
  }
  if (jwk['alg'] !== undefined && jwk['alg'] !== alg) {
    throw new SigningKeyError('alg_key_mismatch', `Key is published for ${String(jwk['alg'])}, not ${alg}`);
  }
  const expected = keyTypeForAlgorithm(alg);
  if (jwk['kty'] !== expected.kty) {
    throw new SigningKeyError('alg_key_mismatch', `${alg} requires a ${expected.kty} key, got ${String(jwk['kty'])}`);
  }
  if (expected.kty === 'RSA') {
    if (typeof jwk['n'] !== 'string' || typeof jwk['e'] !== 'string') {
      throw new SigningKeyError('invalid_key', 'RSA key is missing n or e');
    }
    if (base64UrlByteLength(jwk['n']) * 8 < MIN_RSA_MODULUS_BITS) {
      throw new SigningKeyError('invalid_key', `RSA modulus must be at least ${MIN_RSA_MODULUS_BITS} bits`);
    }
  } else {
    if (jwk['crv'] !== 'P-256') {
      throw new SigningKeyError('alg_key_mismatch', `ES256 requires curve P-256, got ${String(jwk['crv'])}`);
    }
    if (typeof jwk['x'] !== 'string' || typeof jwk['y'] !== 'string') {
      throw new SigningKeyError('invalid_key', 'EC key is missing x or y');
    }
  }
}

function publicMembers(jwk: JWK, alg: SigningAlgorithm): JWK {
  const names = alg === 'RS256' ? ['kty', 'n', 'e'] as const : ['kty', 'crv', 'x', 'y'] as const;
  const result: Record<string, string> = {};
  for (const name of names) {
    const value = jwk[name];
    if (typeof value === 'string') result[name] = value;
  }
  return result as JWK;
}

function assertKid(kid: string): void {
  if (!KID_RE.test(kid)) {
    throw new SigningKeyError('invalid_key', 'A key id must be 1-128 characters of A-Z a-z 0-9 . _ : -');
  }
}

/** `grantex-<alg>-<first 16 chars of the RFC 7638 thumbprint>`. */
export async function thumbprintKid(alg: SigningAlgorithm, publicJwk: JWK): Promise<string> {
  const thumbprint = await calculateJwkThumbprint(publicMembers(publicJwk, alg), 'sha256');
  return `grantex-${alg.toLowerCase()}-${thumbprint.slice(0, 16)}`;
}

/** The kid historically used for the RS256 key: `grantex-YYYY-MM` of the start date. */
export function legacyRsaKid(now: Date = new Date()): string {
  const month = String(now.getUTCMonth() + 1).padStart(2, '0');
  return `grantex-${now.getUTCFullYear()}-${month}`;
}

async function buildSigningKey(
  alg: SigningAlgorithm,
  kid: string,
  publicJwk: JWK,
  privateKey: KeyLike | null,
): Promise<SigningKey> {
  assertKid(kid);
  const members = publicMembers(publicJwk, alg);
  assertPublicJwkForAlgorithm(members as Record<string, unknown>, alg);
  const publicKey = await importJWK(members, alg) as KeyLike;
  return {
    kid,
    alg,
    publicJwk: { ...members, kid, alg, use: 'sig' },
    publicKey,
    privateKey,
    status: privateKey === null ? 'retired' : 'active',
  };
}

function asActive(key: SigningKey): ActiveSigningKey {
  if (key.privateKey === null) throw new SigningKeyError('no_signing_key', 'The active signing key has no private key');
  return { ...key, privateKey: key.privateKey, status: 'active' };
}

/** Import a PKCS#8 PEM private key for `alg` and derive its public key. */
export async function importPrivateKeyPem(
  pem: string,
  alg: SigningAlgorithm,
  settingName: string,
): Promise<{ privateKey: KeyLike; publicJwk: JWK }> {
  let privateKey: KeyLike;
  try {
    privateKey = await importPKCS8(pem.replace(/\\n/g, '\n'), alg, { extractable: true });
  } catch (err) {
    const detail = err instanceof Error ? err.message : String(err);
    const expected = alg === 'RS256' ? 'an RSA' : 'an EC P-256';
    throw new SigningKeyError('invalid_key', `${settingName} must be ${expected} private key in PKCS#8 PEM form (${detail})`);
  }
  const jwk = await exportJWK(privateKey);
  const publicJwk = publicMembers(jwk, alg);
  assertPublicJwkForAlgorithm(publicJwk as Record<string, unknown>, alg);
  return { privateKey, publicJwk };
}

export async function generateSigningKeyMaterial(alg: SigningAlgorithm): Promise<{ privateKey: KeyLike; publicJwk: JWK }> {
  const { privateKey, publicKey } = alg === 'RS256'
    ? await generateKeyPair('RS256', { modulusLength: MIN_RSA_MODULUS_BITS, extractable: true })
    : await generateKeyPair('ES256', { extractable: true });
  return { privateKey, publicJwk: await exportJWK(publicKey) };
}

/**
 * Parse `JWT_RETIRED_PUBLIC_KEYS`: a JWK Set whose keys each carry `kid` and
 * `alg` (RS256 or ES256) and only public members.
 */
export async function parseRetiredPublicKeys(value: string | null): Promise<SigningKey[]> {
  if (value === null || value.trim() === '') return [];
  let parsed: unknown;
  try {
    parsed = JSON.parse(value);
  } catch {
    throw new SigningKeyError('invalid_key', 'JWT_RETIRED_PUBLIC_KEYS must be a JSON Web Key Set');
  }
  const keys = typeof parsed === 'object' && parsed !== null && !Array.isArray(parsed)
    ? (parsed as Record<string, unknown>)['keys']
    : undefined;
  if (!Array.isArray(keys)) {
    throw new SigningKeyError('invalid_key', 'JWT_RETIRED_PUBLIC_KEYS must be a JSON Web Key Set with a keys array');
  }
  const result: SigningKey[] = [];
  for (const [index, raw] of keys.entries()) {
    if (typeof raw !== 'object' || raw === null || Array.isArray(raw)) {
      throw new SigningKeyError('invalid_key', `JWT_RETIRED_PUBLIC_KEYS keys[${index}] must be an object`);
    }
    const jwk = raw as Record<string, unknown>;
    const alg = jwk['alg'];
    const kid = jwk['kid'];
    if (!isSigningAlgorithm(alg)) {
      throw new SigningKeyError('unsupported_alg', `JWT_RETIRED_PUBLIC_KEYS keys[${index}].alg must be one of ${SIGNING_ALGORITHMS.join(', ')}`);
    }
    if (typeof kid !== 'string') {
      throw new SigningKeyError('invalid_key', `JWT_RETIRED_PUBLIC_KEYS keys[${index}].kid must be a string`);
    }
    assertPublicJwkForAlgorithm(jwk, alg);
    result.push(await buildSigningKey(alg, kid, jwk as JWK, null));
  }
  return result;
}

// ─── env store ───────────────────────────────────────────────────────────────

export interface EnvKeyRingOptions {
  alg: SigningAlgorithm;
  rsaPrivateKey: string | null;
  ecPrivateKey: string | null;
  autoGenerate: boolean;
  /** Overrides the kid of the signing key. */
  kid: string | null;
  retiredPublicKeys: string | null;
  now?: Date;
}

async function envKid(alg: SigningAlgorithm, publicJwk: JWK, now: Date): Promise<string> {
  // The RS256 key keeps the kid it has always had, so upgrading does not
  // change the published key id.
  return alg === 'RS256' ? legacyRsaKid(now) : thumbprintKid(alg, publicJwk);
}

export async function loadEnvSigningKeyRing(options: EnvKeyRingOptions): Promise<SigningKeyRing> {
  const now = options.now ?? new Date();
  const pems: Record<SigningAlgorithm, { pem: string | null; setting: string }> = {
    RS256: { pem: options.rsaPrivateKey, setting: 'RSA_PRIVATE_KEY' },
    ES256: { pem: options.ecPrivateKey, setting: 'EC_PRIVATE_KEY' },
  };

  const signing = pems[options.alg];
  let material: { privateKey: KeyLike; publicJwk: JWK };
  if (signing.pem) {
    material = await importPrivateKeyPem(signing.pem, options.alg, signing.setting);
  } else if (options.autoGenerate) {
    material = await generateSigningKeyMaterial(options.alg);
  } else {
    const what = options.alg === 'RS256' ? 'No RSA key configured' : 'No EC P-256 key configured';
    throw new SigningKeyError(
      'no_signing_key',
      `${what} for JWT_SIGNING_ALG=${options.alg}: set ${signing.setting} or AUTO_GENERATE_KEYS=true`,
    );
  }
  const activeKid = options.kid ?? await envKid(options.alg, material.publicJwk, now);
  const active = asActive(await buildSigningKey(options.alg, activeKid, material.publicJwk, material.privateKey));

  const verificationOnly: SigningKey[] = [];
  for (const alg of SIGNING_ALGORITHMS) {
    if (alg === options.alg) continue;
    const other = pems[alg];
    if (!other.pem) continue;
    const imported = await importPrivateKeyPem(other.pem, alg, other.setting);
    // Published for verification only: the private key is not kept.
    verificationOnly.push(await buildSigningKey(alg, await envKid(alg, imported.publicJwk, now), imported.publicJwk, null));
  }
  verificationOnly.push(...await parseRetiredPublicKeys(options.retiredPublicKeys));
  return new SigningKeyRing(active, verificationOnly);
}

// ─── postgres store ──────────────────────────────────────────────────────────

interface KeyRow {
  kid: string;
  algorithm: string;
  public_key_jwk: Record<string, unknown>;
  encrypted_private_key_jwk: string | null;
  status: string;
}

const KEY_TABLE_LOCK = 'grantex:platform_signing_keys';

async function rowToKey(row: KeyRow): Promise<SigningKey> {
  if (!isSigningAlgorithm(row.algorithm)) {
    throw new SigningKeyError('unsupported_alg', `Stored signing key ${row.kid} has unsupported algorithm ${row.algorithm}`);
  }
  const alg = row.algorithm;
  if (row.status === 'active') {
    if (row.encrypted_private_key_jwk === null) {
      throw new SigningKeyError('no_signing_key', `Active signing key ${row.kid} has no private key`);
    }
    const privateJwk = JSON.parse(decrypt(row.encrypted_private_key_jwk)) as JWK;
    const privateKey = await importJWK(privateJwk, alg) as KeyLike;
    const derived = publicMembers(privateJwk, alg);
    const stored = publicMembers(row.public_key_jwk as JWK, alg);
    if (JSON.stringify(derived) !== JSON.stringify(stored)) {
      throw new SigningKeyError('invalid_key', `Stored signing key ${row.kid} does not match its private key`);
    }
    return buildSigningKey(alg, row.kid, stored, privateKey);
  }
  return buildSigningKey(alg, row.kid, row.public_key_jwk as JWK, null);
}

async function insertActiveKey(tx: Sql, alg: SigningAlgorithm): Promise<string> {
  const material = await generateSigningKeyMaterial(alg);
  const kid = await thumbprintKid(alg, material.publicJwk);
  const privateJwk = await exportJWK(material.privateKey);
  const publicJwk = { ...publicMembers(material.publicJwk, alg), kid, alg, use: 'sig' };
  await tx`
    INSERT INTO platform_signing_keys (kid, algorithm, public_key_jwk, encrypted_private_key_jwk, status)
    VALUES (${kid}, ${alg}, ${tx.json(publicJwk as never)}, ${encrypt(JSON.stringify(privateJwk))}, 'active')
  `;
  return kid;
}

async function selectRing(sql: Sql, retiredGraceSeconds: number): Promise<SigningKeyRing | null> {
  const rows = await sql<KeyRow[]>`
    SELECT kid, algorithm, public_key_jwk, encrypted_private_key_jwk, status
      FROM platform_signing_keys
     WHERE status = 'active'
        OR (status = 'retired' AND retired_at > NOW() - make_interval(secs => ${retiredGraceSeconds}))
     ORDER BY (status = 'active') DESC, created_at DESC
  `;
  const activeRows = rows.filter((row) => row.status === 'active');
  if (activeRows.length === 0) return null;
  if (activeRows.length > 1) {
    throw new SigningKeyError('duplicate_kid', 'More than one active platform signing key is stored');
  }
  const [active, ...rest] = await Promise.all(rows.map(rowToKey));
  return new SigningKeyRing(asActive(active!), rest);
}

export interface PostgresKeyRingOptions {
  /** Algorithm for the first key when none is stored. */
  alg: SigningAlgorithm;
  retiredGraceSeconds: number;
}

/**
 * Load the stored key set, generating and storing the first key when none
 * exists. The stored active key signs even when its algorithm differs from
 * `alg`: changing algorithm is a rotation (`rotatePostgresSigningKey`), so
 * instances with different settings cannot rotate against each other.
 */
export async function loadPostgresSigningKeyRing(sql: Sql, options: PostgresKeyRingOptions): Promise<SigningKeyRing> {
  const existing = await selectRing(sql, options.retiredGraceSeconds);
  if (existing) return existing;
  await sql.begin(async (tx) => {
    const t = tx as unknown as Sql;
    await t`SELECT pg_advisory_xact_lock(hashtextextended(${KEY_TABLE_LOCK}, 0))`;
    const active = await t<{ kid: string }[]>`SELECT kid FROM platform_signing_keys WHERE status = 'active'`;
    if (active.length === 0) await insertActiveKey(t, options.alg);
  });
  const ring = await selectRing(sql, options.retiredGraceSeconds);
  if (!ring) throw new SigningKeyError('no_signing_key', 'No active platform signing key after generation');
  return ring;
}

/** Reload the stored key set without generating a key. */
export async function reloadPostgresSigningKeyRing(sql: Sql, retiredGraceSeconds: number): Promise<SigningKeyRing> {
  const ring = await selectRing(sql, retiredGraceSeconds);
  if (!ring) throw new SigningKeyError('no_signing_key', 'No active platform signing key is stored');
  return ring;
}

/**
 * Retire the active key (erasing its private key) and store a new active key
 * for `alg`, atomically. Returns the retired and new key ids.
 */
export async function rotatePostgresSigningKey(
  sql: Sql,
  alg: SigningAlgorithm,
): Promise<{ retiredKid: string | null; kid: string; alg: SigningAlgorithm }> {
  let retiredKid: string | null = null;
  let kid = '';
  await sql.begin(async (tx) => {
    const t = tx as unknown as Sql;
    await t`SELECT pg_advisory_xact_lock(hashtextextended(${KEY_TABLE_LOCK}, 0))`;
    const retired = await t<{ kid: string }[]>`
      UPDATE platform_signing_keys
         SET status = 'retired', retired_at = NOW(), encrypted_private_key_jwk = NULL
       WHERE status = 'active'
      RETURNING kid
    `;
    retiredKid = retired[0]?.kid ?? null;
    kid = await insertActiveKey(t, alg);
  });
  return { retiredKid, kid, alg };
}

// ─── Process key set and verification ────────────────────────────────────────

let currentRing: SigningKeyRing | null = null;
let reloader: (() => Promise<SigningKeyRing>) | null = null;
let lastReloadAt = 0;
export const UNKNOWN_KID_RELOAD_COOLDOWN_MS = 30_000;

export function setSigningKeyRing(ring: SigningKeyRing, reload: (() => Promise<SigningKeyRing>) | null = null): void {
  currentRing = ring;
  reloader = reload;
  lastReloadAt = Date.now();
}

export function getSigningKeyRing(): SigningKeyRing {
  if (!currentRing) throw new SigningKeyError('keys_not_initialized', 'Keys not initialized — call initKeys() first');
  return currentRing;
}

/** Reload from the store now (postgres store only). Returns false when there is no store to reload. */
export async function reloadSigningKeyRing(): Promise<boolean> {
  if (!reloader) return false;
  currentRing = await reloader();
  lastReloadAt = Date.now();
  return true;
}

/**
 * Resolve the platform key for a JWS protected header. Used as the key
 * argument of `jwtVerify` together with `algorithms: SIGNING_ALGORITHMS`.
 *
 * - `alg` must be RS256 or ES256.
 * - With a `kid`, that key must exist (after at most one reload per cooldown
 *   for the postgres store) and be published for the same `alg`.
 * - Without a `kid`, only the active key is tried, and only for its `alg`.
 */
export async function resolvePlatformVerificationKey(header: JWTHeaderParameters): Promise<KeyLike> {
  const ring = getSigningKeyRing();
  const alg = header.alg;
  if (!isSigningAlgorithm(alg)) {
    throw new SigningKeyError('unsupported_alg', `Token algorithm ${String(alg)} is not allowed`);
  }
  if (header.kid === undefined) {
    if (ring.active.alg !== alg) {
      throw new SigningKeyError('missing_kid', `Token has no kid and the signing key is not ${alg}`);
    }
    return ring.active.publicKey;
  }
  if (typeof header.kid !== 'string' || header.kid.length === 0) {
    throw new SigningKeyError('missing_kid', 'Token kid must be a non-empty string');
  }
  let key = ring.get(header.kid);
  if (key === undefined && reloader && Date.now() - lastReloadAt >= UNKNOWN_KID_RELOAD_COOLDOWN_MS) {
    await reloadSigningKeyRing();
    key = getSigningKeyRing().get(header.kid);
  }
  if (key === undefined) {
    throw new SigningKeyError('unknown_kid', `No platform signing key has kid ${header.kid}`);
  }
  if (key.alg !== alg) {
    throw new SigningKeyError('alg_key_mismatch', `Key ${key.kid} is published for ${key.alg}, not ${alg}`);
  }
  return key.publicKey;
}
