/**
 * spec/examples/signing-keys-legacy-kid.json: the JWK Set this service serves
 * on 2026-09-01 for an RS256 key (with its legacy grantex-YYYY-MM aliases) and
 * an ES256 key, plus tokens signed with those keys. The SDK test suites verify
 * the tokens against this JWK Set, so a pre-0.6 token signed on 2026-08-31
 * is checked end to end in every verifier.
 *
 * Regenerate with GRANTEX_WRITE_FIXTURES=1 (new keys each time; the private
 * keys are discarded). Without it, this test checks the committed fixture
 * against the code that publishes keys.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { SignJWT, createLocalJWKSet, exportPKCS8, generateKeyPair, jwtVerify, type CryptoKey, type JWK } from 'jose';
import { initKeys } from '../src/lib/crypto.js';
import {
  SigningKeyRing,
  legacyKidsForWindow,
  loadEnvSigningKeyRing,
  parseVerificationPublicKeys,
  publishedSigningJwks,
  resolvePlatformVerificationKey,
  setLegacyKidPolicy,
  setSigningKeyRing,
  thumbprintKid,
} from '../src/lib/signing-keys.js';

const FIXTURE = join(dirname(fileURLToPath(import.meta.url)), '..', '..', '..', 'spec', 'examples', 'signing-keys-legacy-kid.json');
const SERVED_AT = '2026-09-01T00:00:00Z';
const LEGACY_MONTHS = 13;
const ISSUER = 'https://auth.example.com';
const FAR_FUTURE = 4_102_444_800; // 2100-01-01

interface Fixture {
  description: string;
  served_at: string;
  issuer: string;
  jwks: { keys: Array<Record<string, unknown>> };
  tokens: Record<'legacy_kid_rs256' | 'thumbprint_rs256' | 'thumbprint_es256', { kid: string; alg: string; token: string }>;
  claims: Record<string, unknown>;
}

const CLAIMS = {
  sub: 'user_01EXAMPLEPRINCIPAL',
  agt: 'did:grantex:ag_01EXAMPLEAGENT',
  dev: 'dev_01EXAMPLE',
  scp: ['tool:acme_kyb:read'],
  scope: 'tool:acme_kyb:read',
  grnt: 'grnt_01EXAMPLEGRANT',
  client_id: 'ag_01EXAMPLEAGENT',
};

async function sign(key: CryptoKey, alg: 'RS256' | 'ES256', kid: string, jti: string, iat: string): Promise<string> {
  return new SignJWT(CLAIMS)
    .setProtectedHeader({ alg, kid, typ: 'at+jwt' })
    .setIssuer(ISSUER).setJti(jti)
    .setIssuedAt(Math.floor(Date.parse(iat) / 1000))
    .setExpirationTime(FAR_FUTURE)
    .sign(key);
}

afterAll(async () => {
  await initKeys();
});

if (process.env['GRANTEX_WRITE_FIXTURES'] === '1') {
  it('writes the fixture', async () => {
    const rsa = await generateKeyPair('RS256', { modulusLength: 2048, extractable: true });
    const ec = await generateKeyPair('ES256', { extractable: true });
    const ring = await loadEnvSigningKeyRing({
      alg: 'RS256', rsaPrivateKey: await exportPKCS8(rsa.privateKey), ecPrivateKey: await exportPKCS8(ec.privateKey),
      autoGenerate: false, verificationPublicKeys: null, legacyKidKey: null,
    });
    setSigningKeyRing(ring);
    setLegacyKidPolicy({ months: LEGACY_MONTHS, transitionSeconds: 0, startedAt: new Date(SERVED_AT) });
    const ecKid = ring.keys().find((key) => key.alg === 'ES256')!.kid;
    const fixture: Fixture = {
      description: 'JWK Set served on served_at by an auth service with an RS256 signing key (legacy kid aliases for JWT_LEGACY_KID_MONTHS=13) and an ES256 key, and tokens signed by those keys. legacy_kid_rs256 is a pre-0.6 token signed on 2026-08-31 with kid grantex-2026-08. Generated by apps/auth-service/tests/signing-keys-fixture.test.ts; the private keys were discarded.',
      served_at: SERVED_AT,
      issuer: ISSUER,
      jwks: { keys: publishedSigningJwks(new Date(SERVED_AT)) },
      tokens: {
        legacy_kid_rs256: { kid: 'grantex-2026-08', alg: 'RS256', token: await sign(rsa.privateKey, 'RS256', 'grantex-2026-08', 'tok_legacy', '2026-08-31T23:30:00Z') },
        thumbprint_rs256: { kid: ring.active.kid, alg: 'RS256', token: await sign(rsa.privateKey, 'RS256', ring.active.kid, 'tok_rs256', '2026-09-01T00:30:00Z') },
        thumbprint_es256: { kid: ecKid, alg: 'ES256', token: await sign(ec.privateKey, 'ES256', ecKid, 'tok_es256', '2026-09-01T00:30:00Z') },
      },
      claims: { iss: ISSUER, ...CLAIMS, exp: FAR_FUTURE },
    };
    writeFileSync(FIXTURE, `${JSON.stringify(fixture, null, 2)}\n`);
  });
}

describe('signing-keys-legacy-kid fixture', () => {
  let fixture: Fixture;
  let signerKid: string;
  beforeAll(async () => {
    fixture = JSON.parse(readFileSync(FIXTURE, 'utf8')) as Fixture;
    // An auth service that holds the fixture's public keys, with the RSA key
    // as the legacy kid key, on served_at.
    const [rsaEntry, ...rest] = fixture.jwks.keys;
    const ecEntry = rest.find((key) => key['alg'] === 'ES256')!;
    const [rsaKey, ecKey] = await parseVerificationPublicKeys(JSON.stringify({ keys: [rsaEntry, ecEntry] }));
    const signer = await loadEnvSigningKeyRing({
      alg: 'ES256', rsaPrivateKey: null, ecPrivateKey: null, autoGenerate: true, verificationPublicKeys: null, legacyKidKey: null,
    });
    signerKid = signer.active.kid;
    setSigningKeyRing(new SigningKeyRing(signer.active, [{ ...rsaKey!, legacyKidAlias: true }, ecKey!]));
    setLegacyKidPolicy({ months: LEGACY_MONTHS, transitionSeconds: 0, startedAt: new Date(fixture.served_at) });
  });

  it('is the JWK Set this code publishes on served_at for its keys', async () => {
    const [rsaEntry, ecEntry] = fixture.jwks.keys;
    expect(rsaEntry!['kid']).toBe(await thumbprintKid('RS256', rsaEntry as JWK));
    expect(ecEntry!['kid']).toBe(await thumbprintKid('ES256', ecEntry as JWK));
    const expected = publishedSigningJwks(new Date(fixture.served_at)).filter((key) => key['kid'] !== signerKid);
    expect(fixture.jwks.keys).toEqual(expected);
    expect(expected.slice(2).map((key) => key['kid'])).toEqual(legacyKidsForWindow(new Date(fixture.served_at), LEGACY_MONTHS));
  });

  it('every token verifies with a stock verifier against the served JWK Set', async () => {
    const jwks = createLocalJWKSet(fixture.jwks);
    for (const [name, entry] of Object.entries(fixture.tokens)) {
      const { payload, protectedHeader } = await jwtVerify(entry.token, jwks, { algorithms: ['RS256', 'ES256'], issuer: fixture.issuer });
      expect([name, protectedHeader.kid, protectedHeader.alg]).toEqual([name, entry.kid, entry.alg]);
      expect(payload).toMatchObject(fixture.claims);
    }
  });

  it('every token, including the 2026-08 legacy kid, verifies in the auth service on served_at', async () => {
    for (const entry of Object.values(fixture.tokens)) {
      await expect(jwtVerify(entry.token, resolvePlatformVerificationKey, { algorithms: ['RS256', 'ES256'], issuer: fixture.issuer }))
        .resolves.toBeDefined();
    }
  });
});
